### ISSUE TITLE
Heart rate monitor

### ISSUE THREAD

**Issue by mnfedwolf** [ls6777/FitbitWatchAnalogClock#1]
Great clock face but unfortunately the heart rate is off the main screen of the versa 2. It seems like it just needs a lot be deleted.  Can you help out?

**Comment by ls6777** [comment]
Hmm... interesting.  I thought the versa and versa 2 had the same screen dimensions.  I'm going on vacation next week, but I'm getting a Versa 2 shipped to me early next week.  I'll check it out on there and resolve this as soon as I get back from vacation.

**Comment by mnfedwolf** [comment]
Yea the left side of the screen the stat fit but the lower right, there is
a space between the ❤️ and the actual number below it. Thanks have a a
great vacation

**Comment by ls6777** [comment]
It's weird because it looks correct on the versa 2 simulator. Once I get it on the real device, I can see if I'm getting the same results as you.

**Comment by mnfedwolf** [comment]
Shot of my versa 2

**Comment by ls6777** [comment]
I'm not seeing any attachments on your message.

**Comment by mnfedwolf** [comment]
Now?

**Comment by ls6777** [comment]
Nope.  Are you dropping your attachment in the comment area?  I just tested it with a picture and it showed up fine.  What file type are you trying to attach?

**Comment by ls6777** [comment]
![IMG_20200521_181555](https://user-images.githubusercontent.com/26239627/89003960-f46e3c00-d2b5-11ea-8978-774ad0155ed2.jpg)

**Comment by mnfedwolf** [comment]
IMG_20200730_232738~2.jpg
<https://drive.google.com/file/d/1jBp-vP4jvtiTirkl4WIb7Ct6caUFDlka/view?usp=drivesdk>

**Comment by ls6777** [comment]
Ok... I looked at the screenshot you sent.  I don't see anything wrong there. the "--" is in the correct location.  The "--" means that the HR sensor is not on/enabled or reading anything.

What are your HR settings on the Versa 2?

**Comment by ls6777** [comment]
Appears to be working as designed/intended.
