### ISSUE TITLE
Temperature 

### ISSUE THREAD

**Issue by chrisgrange** [ls6777/FitbitWatchAnalogClock#2]
Hi. When selecting the B&W analogue with stats. It’s shows the temperature in degrees Celsius. I have chosen this watch face and it is in degrees Fahrenheit. Is this something that can be changed as I want it to be in Celsius like it shows when selecting it.

**Comment by ls6777** [comment]
Hi.  The units for temperature and elevation are determined by the Units you select in your Fitbit profile.  You must change the "Length" units from "Feet, Miles" to "Centimeters, Kilometers" in the _Advanced Settings_ under your profile in the Fitbit app on your phone.  If you're still having issues, please reopen this issue.

**Comment by chrisgrange** [comment]
> Hi. The units for temperature and elevation are determined by the Units you select in your Fitbit profile. You must change the "Length" units from "Feet, Miles" to "Centimeters, Kilometers" in the _Advanced Settings_ under your profile in the Fitbit app on your phone. If you're still having issues, please reopen this issue.

I do have it in centimetres

**Comment by ls6777** [comment]
Hmm... let me look into this a bit.

**Comment by ls6777** [comment]
I'm heading out for vacation shortly for the next week.  I will look into this more when I get back.  Not sure why it's not linked to the length unit.  It might be linked to location.  I will resolve this when I get back.

**Comment by chrisgrange** [comment]
Please open this as it hasn’t worked doing that

**Comment by chrisgrange** [comment]
This is working now. I deselected the watch face and applied it again. So that’s what you need to do
If this problem happens for anyone else. Thanks for your help

**Comment by ls6777** [comment]
Glad you were able to resolve it!  Good info for me for future users! :)
