### ISSUE TITLE
I can't see the full display of https://github.com/ls6777/FitbitWatchAnalogClock

### ISSUE THREAD

**Issue by aruniki** [ls6777/FitbitWatchAnalogClock#4]
I can't see the full display of this b&w analog clock. It's truncating top and bottom stats.

Thanks
Arun

**Comment by ls6777** [comment]
Hi Arjun,

Can you attach a picture so I can see what you’re issue is?

**Comment by ls6777** [comment]
Closing this issue since I never got a response.  Likely, the issue is the same as what's been reported before.  Which is that people perceive "--" as truncating, which is not the case. "--" indicates that the sensor is not enabled, or it can't read a valid value.
